# Generated by Django 2.0 on 2018-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='premier_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('email', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
