# Generated by Django 2.0 on 2018-07-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premier_users',
            old_name='email',
            new_name='email_address',
        ),
    ]
