# Generated by Django 2.0 on 2018-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0003_auto_20180716_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premier_users',
            old_name='name',
            new_name='first_Name',
        ),
        migrations.AddField(
            model_name='premier_users',
            name='last_Name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='premier_users',
            name='middle_Name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
