# Generated by Django 2.0 on 2018-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0005_auto_20180717_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_users',
            name='first_Name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
