# Generated by Django 2.0 on 2018-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0006_auto_20180717_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_users',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='premier_users',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
