# Generated by Django 2.0 on 2018-07-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0007_auto_20180717_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premier_users',
            old_name='first_Name',
            new_name='names',
        ),
        migrations.RemoveField(
            model_name='premier_users',
            name='last_Name',
        ),
        migrations.RemoveField(
            model_name='premier_users',
            name='middle_Name',
        ),
    ]
