# Generated by Django 2.0 on 2018-07-18 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prem_test', '0008_auto_20180717_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='premier_users',
            name='branch_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
